language: node_js

node_js:
  - "10"

cache:
  apt: true
  directories:
    - node_modules

addons:
  ssh_known_hosts: $DEPLOY_IP

script:
  - hexo clean && hexo generate

before_deploy:
- openssl aes-256-cbc -K $encrypted_25ad2a76f550_key -iv $encrypted_25ad2a76f550_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

after_success:
  - pwd
  - scp -o StrictHostKeyChecking=no -r public/*  root@$DEPLOY_IP:/opt/hexoBlog/

branches:
  only:
    - master

notifications:
  email:
    - huguobo2010@126.com
  on_success: change
  on_failure: always