language: node_js

node_js:
  - "10"

cache:
  apt: true
  directories:
    - node_modules

addons:
  ssh_known_hosts: $DEPLOY_IP

install:
  - npm install

script:
  - hexo clean 
  - hexo g

before_deploy:
- openssl aes-256-cbc -K $encrypted_25ad2a76f550_key -iv $encrypted_25ad2a76f550_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -e "ssh -o PubkeyAuthentication=yes  -o stricthostkeychecking=no" -r --delete-after --quiet $TRAVIS_BUILD_DIR/public root@$DEPLOY_IP:/opt/hexoBlog
  on:
    branch: master

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: scp -o StrictHostKeyChecking=no -r public/*  root@$DEPLOY_IP:/opt/hexoBlog/
#   on:
#      branch: master

branches:
  only:
    - master

notifications:
  email:
    - huguobo2010@126.com
  on_success: change
  on_failure: always