language: node_js

node_js:
  - "10"

cache:
  apt: true
  directories:
    - node_modules

install:
  - npm install hexo-cli@2.0.0 -g
  - npm install

script:
  - hexo clean 
  - hexo g

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

notifications:
  email:
    - huguobo2010@126.com
  on_success: change
  on_failure: always